// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csjfikajvcrrhzokxtrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzamZpa2FqdmNycmh6b2t4dHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTUzNjAsImV4cCI6MjA2OTk3MTM2MH0.o5r-gV0Z4r3t_yvaMIOnputyWCtTtJnQ-MzrC61a3pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});